access_control:
  enabled: true
  policies:
  - plan:
    - '*'
    apply_force: ['*']
    tag_query: ''

engine:
  name: tofu

workflows:
  - tag_query: ''
    plan:
      - type: run
        cmd: ['false']
        on_error:
          - type: gate
            token: foobar
            all_of: ['user:terrateam-test-user02']
      - type: init
      - type: plan


cost_estimation:
  enabled: false
